package com.scores.demo.mbg.mapper;

import com.scores.demo.mbg.model.StudentScore;
import com.scores.demo.mbg.model.StudentScoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    int countByExample(StudentScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    int deleteByExample(StudentScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    int insert(StudentScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    int insertSelective(StudentScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    List<StudentScore> selectByExample(StudentScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    StudentScore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    int updateByExampleSelective(@Param("record") StudentScore record, @Param("example") StudentScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    int updateByExample(@Param("record") StudentScore record, @Param("example") StudentScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    int updateByPrimaryKeySelective(StudentScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    int updateByPrimaryKey(StudentScore record);
}