package com.scores.demo.mbg.model;

import java.io.Serializable;

public class Courses implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.id
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.coursename
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    private String coursename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table courses
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.id
     *
     * @return the value of courses.id
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.id
     *
     * @param id the value for courses.id
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.coursename
     *
     * @return the value of courses.coursename
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.coursename
     *
     * @param coursename the value for courses.coursename
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", coursename=").append(coursename);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}