package com.scores.demo.mbg.model;

import java.io.Serializable;

public class StudentScore implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.id
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.number
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.name
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.chinese
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    private String chinese;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.math
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    private String math;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.english
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    private String english;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.physics
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    private String physics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.chemistry
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    private String chemistry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.geography
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    private String geography;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.music
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    private String music;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.draw
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    private String draw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_score.sport
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    private String sport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student_score
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.id
     *
     * @return the value of student_score.id
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.id
     *
     * @param id the value for student_score.id
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.number
     *
     * @return the value of student_score.number
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.number
     *
     * @param number the value for student_score.number
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.name
     *
     * @return the value of student_score.name
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.name
     *
     * @param name the value for student_score.name
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.chinese
     *
     * @return the value of student_score.chinese
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public String getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.chinese
     *
     * @param chinese the value for student_score.chinese
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public void setChinese(String chinese) {
        this.chinese = chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.math
     *
     * @return the value of student_score.math
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public String getMath() {
        return math;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.math
     *
     * @param math the value for student_score.math
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public void setMath(String math) {
        this.math = math;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.english
     *
     * @return the value of student_score.english
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public String getEnglish() {
        return english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.english
     *
     * @param english the value for student_score.english
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public void setEnglish(String english) {
        this.english = english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.physics
     *
     * @return the value of student_score.physics
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public String getPhysics() {
        return physics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.physics
     *
     * @param physics the value for student_score.physics
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public void setPhysics(String physics) {
        this.physics = physics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.chemistry
     *
     * @return the value of student_score.chemistry
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public String getChemistry() {
        return chemistry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.chemistry
     *
     * @param chemistry the value for student_score.chemistry
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public void setChemistry(String chemistry) {
        this.chemistry = chemistry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.geography
     *
     * @return the value of student_score.geography
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public String getGeography() {
        return geography;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.geography
     *
     * @param geography the value for student_score.geography
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public void setGeography(String geography) {
        this.geography = geography;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.music
     *
     * @return the value of student_score.music
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public String getMusic() {
        return music;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.music
     *
     * @param music the value for student_score.music
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public void setMusic(String music) {
        this.music = music;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.draw
     *
     * @return the value of student_score.draw
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public String getDraw() {
        return draw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.draw
     *
     * @param draw the value for student_score.draw
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public void setDraw(String draw) {
        this.draw = draw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_score.sport
     *
     * @return the value of student_score.sport
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public String getSport() {
        return sport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_score.sport
     *
     * @param sport the value for student_score.sport
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    public void setSport(String sport) {
        this.sport = sport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_score
     *
     * @mbggenerated Wed Aug 18 11:03:11 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", number=").append(number);
        sb.append(", name=").append(name);
        sb.append(", chinese=").append(chinese);
        sb.append(", math=").append(math);
        sb.append(", english=").append(english);
        sb.append(", physics=").append(physics);
        sb.append(", chemistry=").append(chemistry);
        sb.append(", geography=").append(geography);
        sb.append(", music=").append(music);
        sb.append(", draw=").append(draw);
        sb.append(", sport=").append(sport);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}